micronaut:
  application:
    name: ${APP_NAME:keymanager-grpc}

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5433/postgres`}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:password}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:POSTGRES}
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1

itau:
  contas:
    url: ${API_ITAU:`http://localhost:9091`}

bcb:
  pix:
    url: ${API_BCB:`http://localhost:8082`}