micronaut:
  application:
    name: desafioPix

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
